function [p, info] = social_power(W, varargin)
%SOCIAL_POWER French-DeGroot social power (left dominant eigenvector).
%
%   p = SOCIAL_POWER(W) returns the vector of social powers for the
%   row-stochastic influence matrix W: the non-negative left eigenvector of W
%   for eigenvalue 1, normalised to sum to one.
%
%   p = SOCIAL_POWER(net) uses net.W.
%
%   [p, info] = SOCIAL_POWER(...) also returns
%       info.eigenspaceDim  dimension of the left eigenspace for eigenvalue 1
%       info.isConsensus    true when that dimension is 1
%       info.residual       norm(p'*W - p'), a numerical sanity check
%       info.minEntry       smallest entry of p before clamping
%
%   Name-value options
%       'Tolerance'  tolerance for the null-space computation (default: the
%                    MATLAB NULL default)
%       'Warn'       warn when the eigenspace is not one-dimensional
%                    (default true)
%
%   INTERPRETATION
%       When the model reaches consensus, W^k -> 1*p' (a RANK-ONE limit) and
%       every agent ends at p'*x(0). So p(i) is the weight of agent i's
%       initial opinion in the group's final position -- French's measure of
%       social power, and a centrality measure generated by a dynamic process
%       rather than postulated from the topology.
%
%       p is also the stationary distribution of the dual Markov chain
%       p(k+1) = p(k) W, and p'*x(k) is CONSERVED for all k, which makes an
%       excellent numerical test. For a doubly stochastic W, p = 1/n and the
%       model reaches average consensus.
%
%       Agents outside the unique closed strong component always receive
%       p(i) = 0: nobody listens to them, so their opinions are forgotten.
%
%   WHEN THE EIGENSPACE IS NOT ONE-DIMENSIONAL
%       The graph then has several closed strong components, consensus is
%       impossible, and no single social-power vector exists. p is returned
%       as NaN; use PREDICT_LIMIT_DEGROOT, which handles the block case.
%
%   See also LAPLACIAN_POWER, GRAPH_REPORT, PREDICT_LIMIT_DEGROOT.

    if isstruct(W)
        if ~isfield(W, 'W')
            error('NDS:socialPower:badStruct', ...
                'A struct input must be a network built by NET_FROM_MATRIX.');
        end
        W = W.W;
    end

    n = validate_row_stochastic(W, 'W');

    opts = parse_options(struct( ...
        'Tolerance', [], ...
        'Warn',      true), varargin, mfilename);

    M = W.' - eye(n);
    if isempty(opts.Tolerance)
        basis = null(M);
    else
        basis = null(M, opts.Tolerance);
    end

    info = struct( ...
        'eigenspaceDim', size(basis, 2), ...
        'isConsensus',   size(basis, 2) == 1, ...
        'residual',      NaN, ...
        'minEntry',      NaN);

    if size(basis, 2) ~= 1
        if opts.Warn
            warning('NDS:socialPower:notUnique', ...
                ['The left eigenspace for eigenvalue 1 has dimension %d, so the ' ...
                 'graph has several closed strong components and consensus is ' ...
                 'impossible. Use PREDICT_LIMIT_DEGROOT for the block limit.'], ...
                size(basis, 2));
        end
        p = NaN(n, 1);
        return;
    end

    p = basis(:, 1);

    total = sum(p);
    if abs(total) < eps(class(p)) * n
        error('NDS:socialPower:degenerate', ...
            ['The left eigenvector sums to zero, which cannot happen for a ' ...
             'genuine stochastic matrix. Check W for numerical corruption.']);
    end
    p = p / total;

    info.minEntry = min(p);
    if info.minEntry < -1e-9
        warning('NDS:socialPower:negativeEntry', ...
            ['Social power has a significantly negative entry (%.3g); the ' ...
             'result may be numerically unreliable.'], info.minEntry);
    end
    p = max(p, 0);
    p = p / sum(p);

    info.residual = norm(p.' * W - p.', Inf);
end
