function p = social_power(W)
%SOCIAL_POWER French-DeGroot social power (left dominant eigenvector).
%
%   p = SOCIAL_POWER(W) solves
%
%       p' = p' W,      p' * 1 = 1,      p >= 0
%
%   returning the n-by-1 vector of social powers of the row-stochastic
%   influence matrix W.
%
%   INTERPRETATION
%       When the model reaches consensus, W^k -> 1 p' and every agent ends at
%       p'x(0). So p_i is the weight of agent i's initial opinion in the
%       group's final position -- French's measure of social power, and a
%       centrality generated by a dynamic process rather than postulated from
%       the topology.
%
%       p is also the stationary distribution of the DUAL MARKOV CHAIN
%       p(k+1) = p(k) W, and p'x(k) is conserved for every k. Agents outside
%       the unique closed strong component get p_i = 0 exactly: nobody
%       listens to them, so their opinions are forgotten.
%
%   The eigenvector is unique only when the graph is rooted. Otherwise there
%   are several closed strong components, consensus is impossible, and this
%   function errors -- use LIMIT_MATRIX(W), which handles that case.
%
%   Example
%       W = [1/2 1/2 0; 1/3 1/3 1/3; 0 1/2 1/2];
%       p = social_power(W)          % [2/7; 3/7; 2/7]
%       norm(p' * W - p')            % zero
%
%   See also LIMIT_MATRIX, GRAPH_SUMMARY, TOTAL_INFLUENCE.

    n = check_square(W, 'W');
    if ~is_row_stochastic(W)
        error('NDS:social_power:notStochastic', ...
            'W must be row-stochastic. Use W = row_stochastic(A).');
    end

    basis = null(W' - eye(n));           % solve p' W = p'

    if size(basis, 2) ~= 1
        error('NDS:social_power:notUnique', ...
            ['The eigenvalue 1 has a %d-dimensional left eigenspace, so the graph ' ...
             'has several closed strong components and consensus is impossible. ' ...
             'Use LIMIT_MATRIX(W) instead.'], size(basis, 2));
    end

    p = basis / sum(basis);              % normalise so that p'*1 = 1
    p = max(p, 0);                       % clean up round-off at exact zeros
    p = p / sum(p);
end
